name: CI

on:
  push:
    tags:
      - "v*"
  # schedule:
  #   - cron: "0 2 * * *"

jobs:
  on-success:
    needs: testing
    runs-on: ubuntu-latest
    container: whatwewant/zmicro:v1
    if: ${{ always() && needs.testing.result == 'success' }}
    steps:
      - name: Notification Feishu
        uses: whatwewant/action-robot-feishu@v0.0.13
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          title: "✅ 自动化测试：${{ github.repository }}"
          text: |
            分支: ${{ github.ref }}
            提交信息: ${{ github.event.head_commit.message }}
            提交人: ${{ github.actor }}
            状态: 构建成功（https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}）

  on-failure:
    needs: testing
    runs-on: ubuntu-latest
    container: whatwewant/zmicro:v1
    if: ${{ always() && needs.testing.result == 'failure' }}
    steps:
      - name: Notification Feishu
        uses: whatwewant/action-robot-feishu@v0.0.13
        with:
          url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL }}
          title: "❌ 自动化测试：${{ github.repository }}"
          text: |
            分支: ${{ github.ref }}
            提交信息: ${{ github.event.head_commit.message }}
            提交人: ${{ github.actor }}
            状态: 构建失败（https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}）

  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
          - macOS-latest

    steps:
      - name: Setup Zmicro
        uses: zmicro-design/action-setup-zmicro@v1

    # steps:
    #   - name: Setup Zmicro Desktop CI
    #     uses: zmicro-design/action-zmicro-desktop-ci@v1
